'use strict';

const DISCLOSURE = 'Generated by skillsdrift — part of a candidate exercise for Atlan, not an Atlan product.';

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  }[c]));
}

// The "State of Skill Drift" living index: headline stats, one card per
// scanned repo (linking to the card HTML already written under out/cards/),
// a weekly-delta strip if a delta has been computed, and the same
// disclosure/CTA every surface carries.
function renderGallery(state, opts = {}) {
  const waitlistUrl = opts.waitlistUrl || process.env.SKILLSDRIFT_WAITLIST_URL || '__WAITLIST_URL__';

  const rows = (state.byRepo || [])
    .map(
      (r) => `    <a class="repo-card" href="cards/${escapeHtml(r.cardSlug || r.slug)}.html">
      <h3>${escapeHtml(r.slug)}</h3>
      <p>${r.ungovernedSkillPercentage}% ungoverned · ${r.skillsScanned} skill(s) · ${r.drifted} drifted</p>
    </a>`
    )
    .join('\n');

  const securityRows = (state.securityCategorySummary || [])
    .map((s) => `<li>${escapeHtml(s.label)}: ${s.count}</li>`)
    .join('\n');

  const skippedRows = (state.reposSkippedDetail || [])
    .map((s) => `<li>${escapeHtml(s.slug)} — ${escapeHtml(s.reason)}</li>`)
    .join('\n');
  const skippedSection = skippedRows
    ? `<h2>Skipped this run (${state.reposSkippedDetail.length})</h2>
  <ul>${skippedRows}</ul>`
    : '';

  const deltaStrip = opts.delta
    ? `<div class="delta-strip">This week: ${opts.delta.newlyDrifted} new drifted, ${opts.delta.newlyOrphaned} newly orphaned. Ungoverned-skill percentage moved ${opts.delta.uspDelta >= 0 ? '+' : ''}${opts.delta.uspDelta} point(s) to ${state.ungovernedSkillPercentage}%.</div>`
    : '';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>State of Skill Drift</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 0; padding: 2.5rem 1.5rem; background: #f6f7fb; color: #16181d; }
  .wrap { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 2rem; margin-bottom: 0.25rem; }
  .stat-row { display: flex; gap: 1rem; flex-wrap: wrap; margin: 1.5rem 0; }
  .stat { background: #fff; border-radius: 12px; padding: 1rem 1.25rem; min-width: 140px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
  .stat .n { font-size: 1.8rem; font-weight: 800; display: block; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
  .repo-card { background: #fff; border-radius: 12px; padding: 1rem 1.25rem; text-decoration: none; color: inherit; box-shadow: 0 1px 3px rgba(0,0,0,0.06); display: block; }
  .repo-card h3 { margin: 0 0 0.4rem; font-size: 1rem; }
  .repo-card p { margin: 0; font-size: 0.85rem; color: #5b6472; }
  .delta-strip { background: #eef1f6; border-radius: 12px; padding: 1rem 1.25rem; margin: 1.5rem 0; font-size: 0.9rem; }
  .disclosure { font-size: 0.8rem; color: #767f8c; margin-top: 2rem; }
  .cta { display: inline-block; background: #16181d; color: #fff; text-decoration: none; padding: 0.65rem 1.2rem; border-radius: 8px; font-size: 0.9rem; font-weight: 600; margin-top: 0.5rem; }
  @media (prefers-color-scheme: dark) {
    body { background: #0f1115; color: #e7e9ee; }
    .stat, .repo-card { background: #181b21; box-shadow: none; }
    .repo-card p { color: #9aa3b2; }
    .delta-strip { background: #23262e; }
    .cta { background: #e7e9ee; color: #0f1115; }
  }
</style>
</head>
<body>
<div class="wrap">
  <h1>State of Skill Drift</h1>
  <p>A living index of public agent-skills repos, rescanned weekly. Candidate-exercise disclosure below.</p>
  <div class="stat-row">
    <div class="stat"><span class="n">${state.ungovernedSkillPercentage}%</span>ungoverned across sample</div>
    <div class="stat"><span class="n">${state.reposScanned}</span>repos scanned</div>
    <div class="stat"><span class="n">${state.totalSkillsScanned}</span>skills scanned</div>
  </div>
  ${deltaStrip}
  <div class="grid">
${rows}
  </div>
  <h2>Security findings by category (category-level only, no repo attribution)</h2>
  <ul>${securityRows || '<li>None found</li>'}</ul>
  ${skippedSection}
  <p class="disclosure">${DISCLOSURE}</p>
  <p><a class="cta" href="${escapeHtml(waitlistUrl)}" rel="noopener">Join the Registry pilot waitlist</a></p>
</div>
</body>
</html>
`;
}

module.exports = { renderGallery };
