#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(__dirname, 'out');

function parseArgs(argv) {
  const opts = {
    current: path.join(OUT_DIR, 'state-of-drift.json'),
    previous: path.join(OUT_DIR, 'state-of-drift.prev.json'),
    outDir: OUT_DIR,
  };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--current') opts.current = argv[++i];
    else if (argv[i] === '--previous') opts.previous = argv[++i];
    else if (argv[i] === '--out-dir') opts.outDir = argv[++i];
  }
  return opts;
}

// "This week: N new drifted, M newly orphaned" — the delta feeds the
// gallery strip and (in a future round) the bot's broadcast mode.
function computeDelta(prev, curr) {
  const prevBySlug = new Map((prev.byRepo || []).map((r) => [r.slug, r]));
  const currBySlug = new Map((curr.byRepo || []).map((r) => [r.slug, r]));

  const newRepos = [...currBySlug.keys()].filter((s) => !prevBySlug.has(s));
  const droppedRepos = [...prevBySlug.keys()].filter((s) => !currBySlug.has(s));

  let newlyDrifted = 0;
  let newlyOrphaned = 0;
  for (const [slug, curEntry] of currBySlug) {
    const prevEntry = prevBySlug.get(slug);
    const prevDrifted = prevEntry ? prevEntry.drifted : 0;
    const prevUnowned = prevEntry ? prevEntry.unowned : 0;
    if (curEntry.drifted > prevDrifted) newlyDrifted += curEntry.drifted - prevDrifted;
    if (curEntry.unowned > prevUnowned) newlyOrphaned += curEntry.unowned - prevUnowned;
  }

  return {
    fromRunId: prev.runId,
    toRunId: curr.runId,
    newRepos,
    droppedRepos,
    newlyDrifted,
    newlyOrphaned,
    uspDelta: (curr.ungovernedSkillPercentage || 0) - (prev.ungovernedSkillPercentage || 0),
  };
}

function renderMarkdown(delta, curr) {
  const lines = [];
  lines.push(`# Weekly delta: ${delta.fromRunId} -> ${delta.toRunId}`);
  lines.push('');
  lines.push(`This week: ${delta.newlyDrifted} new drifted, ${delta.newlyOrphaned} newly orphaned.`);
  lines.push('');
  lines.push(
    `Ungoverned skill percentage moved ${delta.uspDelta >= 0 ? '+' : ''}${delta.uspDelta} point(s) to ${curr.ungovernedSkillPercentage}%.`
  );
  lines.push('');
  if (delta.newRepos.length) lines.push(`New repos scanned: ${delta.newRepos.join(', ')}`);
  if (delta.droppedRepos.length) lines.push(`Repos no longer in the sample: ${delta.droppedRepos.join(', ')}`);
  if (delta.newRepos.length || delta.droppedRepos.length) lines.push('');
  lines.push(
    'This recurs the moment anyone edits a copy again — a scan finds it, only a governed source stops it from coming back.'
  );
  lines.push('');
  lines.push('Generated by skillsdrift — part of a candidate exercise for Atlan, not an Atlan product.');
  return lines.join('\n') + '\n';
}

function main(argv) {
  const opts = parseArgs(argv);
  if (!fs.existsSync(opts.previous)) {
    process.stderr.write(`No previous state file at ${opts.previous} — nothing to diff yet.\n`);
    return 0;
  }
  const prev = JSON.parse(fs.readFileSync(opts.previous, 'utf8'));
  const curr = JSON.parse(fs.readFileSync(opts.current, 'utf8'));
  const delta = computeDelta(prev, curr);
  const md = renderMarkdown(delta, curr);

  fs.mkdirSync(opts.outDir, { recursive: true });
  fs.writeFileSync(path.join(opts.outDir, 'weekly-delta.md'), md, 'utf8');
  fs.writeFileSync(path.join(opts.outDir, 'weekly-delta.json'), JSON.stringify(delta, null, 2) + '\n', 'utf8');

  process.stdout.write(md);
  return 0;
}

if (require.main === module) process.exit(main(process.argv.slice(2)));
module.exports = { main, computeDelta, renderMarkdown };
