'use strict';

const { renderTemplate } = require('./template');
const { scannedPathsSummary, securityCategoryCounts } = require('./redact');

// T5 — state, not judgment: no score, no grade, no leaderboard anywhere in
// this model or template. The USP percentage renders only as a labeled
// count-of-what stat, never as a standalone badge/gauge.
const DISCLOSURE = 'Generated by skillsdrift — part of a candidate exercise for Atlan, not an Atlan product.';
const RECURRENCE_CLOSE =
  'This will drift again the moment a second person edits any of these skills. A scan finds it; only a governed source of truth prevents it.';
const DEFAULT_ORG = 'A team';
const DEFAULT_WAITLIST_URL = '__WAITLIST_URL__';

function layerSummaryFor(scorecard, uspPct, subject) {
  return {
    engineer: `${scorecard.driftedPairs} drifted pair(s), ${scorecard.unowned} unowned, ${scorecard.unversioned} unversioned skill(s) found this scan.`,
    // The ungoverned percentage counts a security-heuristic hit, so quoting it
    // on a third-party card re-attributes by arithmetic what the card declines
    // to state outright.
    team:
      subject === 'own'
        ? `${uspPct}% of scanned skills are ungoverned — no owner, no version, or a security-heuristic hit.`
        : `${scorecard.unowned} of ${scorecard.skillsScanned} scanned skill(s) carry no owner field. Public libraries usually record ownership in git rather than in the skill file.`,
    leader: 'A governance snapshot, not a grade — the number moves on its own unless something governs it.',
  };
}

// report = a skillsdrift v2 `--json` report (artifact/src/report.js
// buildJsonReport shape), produced either by running skillsdrift directly or
// by build/scanner's scan-repo.js/scan-list.js, which call the same library
// function.
//
// opts: { org, waitlistUrl, repoLink, subject }
//
// `subject` is the distinction this card previously lacked, and it matters
// legally, not just editorially:
//
//   'third-party' (default) — a card about someone else's public repository,
//     published by us. Security findings are NOT shown. Naming a real company
//     next to "reverse shell / raw socket redirect" is an accusation, and
//     launch-distribution-ideas.md P1 condition 2 forbids exactly that:
//     "report drift/ownership stats only, not the 'malicious payload'
//     security category, to avoid defamation-adjacent claims about real
//     companies." The ungoverned percentage is also withheld — §3.4 retracts
//     it as a measure of a file convention rather than a problem.
//
//   'own' — a card about the reader's own repository (their own scan, or the
//     GitHub App issue on a repo that installed it). They are entitled to
//     every finding about their own code, so nothing is withheld.
//
// Defaulting to 'third-party' means a caller that forgets to say cannot leak.
function generateCard(report, opts = {}) {
  const subject = opts.subject === 'own' ? 'own' : 'third-party';
  const org = opts.org || DEFAULT_ORG;
  const waitlistUrl =
    opts.waitlistUrl || report.waitlistUrl || process.env.SKILLSDRIFT_WAITLIST_URL || DEFAULT_WAITLIST_URL;
  const scorecard = report.scorecard || {
    skillsScanned: 0,
    driftedPairs: 0,
    unowned: 0,
    unversioned: 0,
    securityFlagged: 0,
  };
  const uspPct = typeof report.ungovernedSkillPercentage === 'number' ? report.ungovernedSkillPercentage : 0;

  const model = {
    org,
    subject,
    // Withheld on a third-party card; see the note on generateCard.
    uspPct: subject === 'own' ? uspPct : null,
    scorecard,
    securityCategories: subject === 'own' ? securityCategoryCounts(report.security) : [],
    showSecurity: subject === 'own',
    scannedPathsLine: scannedPathsSummary(report.scannedPaths),
    layerSummary: layerSummaryFor(scorecard, uspPct, subject),
    recurrenceClose: RECURRENCE_CLOSE,
    disclosure: DISCLOSURE,
    waitlistUrl,
    repoLink: opts.repoLink || null,
  };

  return renderTemplate(model);
}

module.exports = { generateCard, DISCLOSURE, RECURRENCE_CLOSE };
