'use strict';

const { renderTemplate } = require('./template');
const { scannedPathsSummary, securityCategoryCounts } = require('./redact');

// T5 — state, not judgment: no score, no grade, no leaderboard anywhere in
// this model or template. The USP percentage renders only as a labeled
// count-of-what stat, never as a standalone badge/gauge.
const DISCLOSURE = 'Generated by skillsdrift — part of a candidate exercise for Atlan, not an Atlan product.';
const RECURRENCE_CLOSE =
  'This will drift again the moment a second person edits any of these skills. A scan finds it; only a governed source of truth prevents it.';
const DEFAULT_ORG = 'A team';
const DEFAULT_WAITLIST_URL = '__WAITLIST_URL__';

function layerSummaryFor(scorecard, uspPct) {
  return {
    engineer: `${scorecard.driftedPairs} drifted pair(s), ${scorecard.unowned} unowned, ${scorecard.unversioned} unversioned skill(s) found this scan.`,
    team: `${uspPct}% of scanned skills are ungoverned — no owner, no version, or a security-heuristic hit.`,
    leader: 'A governance snapshot, not a grade — the number moves on its own unless something governs it.',
  };
}

// report = a skillsdrift v2 `--json` report (artifact/src/report.js
// buildJsonReport shape), produced either by running skillsdrift directly or
// by build/scanner's scan-repo.js/scan-list.js, which call the same library
// function. opts: { org, waitlistUrl, repoLink }.
function generateCard(report, opts = {}) {
  const org = opts.org || DEFAULT_ORG;
  const waitlistUrl =
    opts.waitlistUrl || report.waitlistUrl || process.env.SKILLSDRIFT_WAITLIST_URL || DEFAULT_WAITLIST_URL;
  const scorecard = report.scorecard || {
    skillsScanned: 0,
    driftedPairs: 0,
    unowned: 0,
    unversioned: 0,
    securityFlagged: 0,
  };
  const uspPct = typeof report.ungovernedSkillPercentage === 'number' ? report.ungovernedSkillPercentage : 0;

  const model = {
    org,
    uspPct,
    scorecard,
    securityCategories: securityCategoryCounts(report.security),
    scannedPathsLine: scannedPathsSummary(report.scannedPaths),
    layerSummary: layerSummaryFor(scorecard, uspPct),
    recurrenceClose: RECURRENCE_CLOSE,
    disclosure: DISCLOSURE,
    waitlistUrl,
    repoLink: opts.repoLink || null,
  };

  return renderTemplate(model);
}

module.exports = { generateCard, DISCLOSURE, RECURRENCE_CLOSE };
